### PR TITLE
cleanup and modernization

### PR DESCRIPTION
**Pull request by ExpandingMan**
I've modernized this package a bit and added some minor features that I needed.

### CODE REVIEW

**Comment by tpapp** [comment]
Thanks. I currently have little bandwidth for this and the other outstanding PRs, but would be happy to add you as a maintainer.

**Comment by ExpandingMan** [comment]
Sure, sounds good, thanks.

**Comment by tpapp** [comment]
This looks good to me. If you have time please add test coverage for new features, if you don't then feel free to merge as is.

**Comment by ExpandingMan** [comment]
As you've clearly experienced, testing this package well is pretty hard, but I've added a couple of token tests at least.  Will merge when tests pass on travis.

**Comment by ExpandingMan** [comment]
I thought you had given me admin to this, but I don't seem to have it.  Please either merge this, or if you give me admin I can merge.  Thanks.

**Comment by tpapp** [comment]
I did invite you, and wrote you a PM on discourse, in the meantime I am merging. Thanks for the great work!

**Pull request merged**
